# frozen_string_literal: true

require_relative "gaffer/version"

module Gaffer
end

require_relative "gaffer/database"
require_relative "gaffer/domain/club"
require_relative "gaffer/domain/player"
require_relative "gaffer/domain/manager"
require_relative "gaffer/domain/league"
require_relative "gaffer/domain/table_row"
require_relative "gaffer/domain/league_table"
require_relative "gaffer/domain/fixture"
require_relative "gaffer/domain/fixture_generator"
require_relative "gaffer/domain/match"
require_relative "gaffer/domain/match_result"
require_relative "gaffer/domain/goal_event"
require_relative "gaffer/domain/scorer_picker"
require_relative "gaffer/domain/match_engine"
require_relative "gaffer/domain/lineup"
require_relative "gaffer/presenters/matchday_squad"
require_relative "gaffer/repositories/base"
require_relative "gaffer/repositories/club_repository"
require_relative "gaffer/repositories/player_repository"
require_relative "gaffer/repositories/manager_repository"
require_relative "gaffer/repositories/league_repository"
require_relative "gaffer/repositories/fixture_repository"
require_relative "gaffer/repositories/match_repository"
require_relative "gaffer/repositories/goal_event_repository"
require_relative "gaffer/domain/scout_report"
require_relative "gaffer/commands/support/scout_report_builder"
require_relative "gaffer/narratives/scout_briefing"
require_relative "gaffer/narratives/board_reaction"
require_relative "gaffer/commands/support/board_reaction_context"
require_relative "gaffer/presenters/board_reaction_tty"
require_relative "gaffer/presenters/league_table_view"
require_relative "gaffer/presenters/league_table_tty"
require_relative "gaffer/presenters/season_fixtures_tty"
require_relative "gaffer/presenters/top_scorers_tty"
require_relative "gaffer/presenters/scout_report_tty"
require_relative "gaffer/presenters/scout_briefing_tty"
require_relative "gaffer/commands/play_match"
require_relative "gaffer/commands/start_league"
require_relative "gaffer/commands/gameweek_play"
require_relative "gaffer/commands/next_fixture"
require_relative "gaffer/commands/league_standings"
require_relative "gaffer/commands/season_fixtures"
require_relative "gaffer/commands/top_scorers"
require_relative "gaffer/commands/support/league_reads"
